version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    depends_on: 
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: pokemon
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    build: 
      context: .
      dockerfile: Dockerfile.phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    depends_on: 
      - db
volumes:
  db_data: {}